"""cellphone

Revision ID: 0eb2a78fb7da
Revises: 3c040d4ec4d1
Create Date: 2023-02-23 19:16:01.570786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0eb2a78fb7da'
down_revision = '3c040d4ec4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cellphone', sa.String(length=255), nullable=True))
    op.drop_column('user', 'cell_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cell_phone', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'cellphone')
    # ### end Alembic commands ###
