"""empty message

Revision ID: 2435ca961775
Revises: ad1a9123d137
Create Date: 2024-04-02 15:52:35.587677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2435ca961775'
down_revision = 'ad1a9123d137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_checkout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('support_button', sa.Boolean(), nullable=False),
    sa.Column('counter', sa.Boolean(), nullable=False),
    sa.Column('color', sa.Boolean(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('ask_email', sa.Boolean(), nullable=False),
    sa.Column('is_exclusive', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_checkout')
    # ### end Alembic commands ###
