"""affiliate

Revision ID: 3df3ebf9f374
Revises: 950993a55953
Create Date: 2024-03-20 18:43:59.533757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df3ebf9f374'
down_revision = '950993a55953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_affiliate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('product', sa.Column('is_affiliation', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('is_visible_in_store', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('affiliation_name', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('cookie_time', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('affiliation_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'affiliation_type')
    op.drop_column('product', 'cookie_time')
    op.drop_column('product', 'affiliation_name')
    op.drop_column('product', 'is_visible_in_store')
    op.drop_column('product', 'is_affiliation')
    op.drop_table('product_affiliate')
    # ### end Alembic commands ###
