"""empty message

Revision ID: 5b6314523aaa
Revises: f9a2b96f9ba9
Create Date: 2024-05-19 20:40:34.898061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b6314523aaa'
down_revision = 'f9a2b96f9ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('custom_commission', sa.Float(), nullable=True))
    op.drop_column('offer', 'is_custom_commission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('is_custom_commission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('offer', 'custom_commission')
    # ### end Alembic commands ###
