"""empty message

Revision ID: 72c06bacdf06
Revises: a6e172f9f98e
Create Date: 2024-02-20 20:36:49.745410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c06bacdf06'
down_revision = 'a6e172f9f98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('warranty_period', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('packing_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'packing_type')
    op.drop_column('product', 'weight')
    op.drop_column('product', 'warranty_period')
    # ### end Alembic commands ###
