"""empty message

Revision ID: 8722f280eaff
Revises: e51504d58ae7
Create Date: 2024-03-01 11:11:53.982342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8722f280eaff'
down_revision = 'e51504d58ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coupon', 'offer', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupon', type_='foreignkey')
    op.drop_column('coupon', 'offer_id')
    # ### end Alembic commands ###
