"""empty message

Revision ID: 90f32da5e6f3
Revises: 43984e72c54f
Create Date: 2024-02-06 15:16:39.247170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f32da5e6f3'
down_revision = '43984e72c54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comission_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'comission_percent')
    # ### end Alembic commands ###
