"""main company init

Revision ID: 91d972c5f83e
Revises: f5a8d2299a4c
Create Date: 2022-07-30 14:45:15.096343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d972c5f83e'
down_revision = 'f5a8d2299a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('cell_phone', sa.String(length=256), nullable=False),
    sa.Column('landline', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('ein', sa.String(length=256), nullable=True),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('facebook', sa.String(length=256), nullable=True),
    sa.Column('instagram', sa.String(length=256), nullable=True),
    sa.Column('app_android', sa.String(length=256), nullable=True),
    sa.Column('app_ios', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('main_company_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('code_post', sa.String(length=256), nullable=True),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('number', sa.String(length=256), nullable=True),
    sa.Column('district', sa.String(length=256), nullable=True),
    sa.Column('complement', sa.String(length=256), nullable=True),
    sa.Column('lat', sa.String(length=256), nullable=True),
    sa.Column('long', sa.String(length=256), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['main_company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_company_address')
    op.drop_table('main_company')
    # ### end Alembic commands ###
