"""main settings

Revision ID: b8f94deaa786
Revises: 3aa865e9b98b
Create Date: 2022-08-01 12:03:46.645527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f94deaa786'
down_revision = '3aa865e9b98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('logo_image_key', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=255), nullable=True),
    sa.Column('second_color', sa.String(length=255), nullable=True),
    sa.Column('third_color', sa.String(length=255), nullable=True),
    sa.Column('fourth_color', sa.String(length=255), nullable=True),
    sa.Column('fifth_color', sa.String(length=255), nullable=True),
    sa.Column('sixth_color', sa.String(length=255), nullable=True),
    sa.Column('primary_text_color', sa.String(length=255), nullable=True),
    sa.Column('second_text_color', sa.String(length=255), nullable=True),
    sa.Column('third_text_color', sa.String(length=255), nullable=True),
    sa.Column('fourth_text_color', sa.String(length=255), nullable=True),
    sa.Column('fifth_text_color', sa.String(length=255), nullable=True),
    sa.Column('sixth_text_color', sa.String(length=255), nullable=True),
    sa.Column('main_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_company_id'], ['main_company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_settings')
    # ### end Alembic commands ###
