"""add user_id in community

Revision ID: f5a8d2299a4c
Revises: 334170c96fcf
Create Date: 2022-06-27 15:34:41.730357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a8d2299a4c'
down_revision = '334170c96fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'community', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community', type_='foreignkey')
    op.drop_column('community', 'user_id')
    # ### end Alembic commands ###
