"""empty message

Revision ID: f9a2b96f9ba9
Revises: 2435ca961775
Create Date: 2024-04-04 19:41:05.865384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a2b96f9ba9'
down_revision = '2435ca961775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_affiliate', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_affiliate', 'status')
    # ### end Alembic commands ###
